Feature/dictionary
darshan-zopsmart/java-intern pull request #3
Opened 2021-01-15 11:14 UTC by darshan-zopsmart

please review the code and the structure.

2021-01-20 07:34 UTC, shubhamjsh5175 commented on src/main/java/com/zs/bodmas/Bodmas.java
> +        Deque<Character> operands = new ArrayDeque<>();
please check for redundancy in line 25 and 27 @darshan-zopsmart

2021-01-20 07:34 UTC, shubhamjsh5175 commented on src/main/java/com/zs/bodmas/Bodmas.java
> +            numbers.push(applyOperation(operands.pop(), numbers.pop(), numbers.pop()));
your program is not giving a correct output. Please debug this and find what is going wrong and discuss with me.
Also take care of the boundary conditions like divide by zero and what if you get some unknown character in you string.

2021-01-22 09:55 UTC, shubhamjsh5175 requested changes

2021-01-22 09:55 UTC, shubhamjsh5175 commented on src/main/java/com/zs/dictionary/Dictionary.java
> +            logger.severe("File not found");
Good use of exception handling .

2021-01-22 09:55 UTC, shubhamjsh5175 commented on src/main/java/com/zs/programs/DecimalToBinary.java
>          return Integer.toBinaryString(decimal);
Do not use in-build function as this assignment is given to check your coding skills.

2021-01-22 09:55 UTC, shubhamjsh5175 commented on src/main/java/com/zs/programs/EmiCalculator.java
>      }
Principle amount can be a non integer.

2021-01-22 09:55 UTC, shubhamjsh5175 commented on src/main/java/com/zs/programs/ExtractWords.java
>          String word = "";
check for logic.

2021-01-22 09:55 UTC, shubhamjsh5175 commented on src/main/java/com/zs/programs/TwoDimensionArraySum.java
>      int twoD[][];
make this static

2021-01-22 09:55 UTC, shubhamjsh5175 commented on .gitignore
>  *.iml
please check why the iml file is included in git

2021-01-22 09:55 UTC, shubhamjsh5175 commented on src/main/java/com/zs/programs/OneDimensionArraySum.java
>          OneDimensionArraySum oneDimensionArraySum = new OneDimensionArraySum();
use default/parametrised constructors.

2021-01-22 11:08 UTC, shubhamjsh5175 approved these changes

2021-01-25 08:34 UTC, nikhilrss approved these changes

2021-01-25 08:34 UTC, nikhil-rss-zs commented on src/main/java/com/zs/dictionary/Dictionary.java
> +import java.util.logging.*;
Fix the auto-imports

2021-01-25 08:34 UTC, nikhil-rss-zs commented on src/main/java/com/zs/dictionary/Dictionary.java
> +    /**
Java docs should be more descriptive

2021-01-25 08:34 UTC, merged